name: FastApi CI/CD

on:
  #trigger
  push:
    branches:
      - main

jobs: 
  CI:
    runs-on: ubuntu-latest
    steps:
      #checkout
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install python virtual env
        run: pip3 install virtualenv

      - name: Virtual env
        uses: actions/cache@v2
        id: cache-venv
        with: 
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: /
            ${{ runner.os }}-venv-

      - name: Activate Virtual env & install dependencies
        run: python -m venv venv && source venv/bin/activate && pip4 install -r requirements.txt
        if: steps.cache-venv.outputs.cashe-hit !- 'true'

      - name: Run tests
        run: . venv/bin/activate && pytest
      
      - name: Create archive of dependencies
        run: /
          cd ./venv/lib/python3.7/site-packages
          zip -r9 ../../../../api.zip
      
      - name: Add API files to zip files
        run: cd ./api && zip -g ../api.zip -r

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2  
        with: 
          name: api
          path: api.zip

          
      


      